oauth.enabled=true

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:126439899123-u6f56799vv2992om8pnr9euggf7cqo69.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
